name: nix-mwe

library:
  dependencies:
  - base
  - inline-r >=0.9 && <0.11
  source-dirs: library

executables:
  nix-mwe:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - nix-mwe
